NETBEGIN 2
CLUBEGIN 1
PERBEGIN 1
CLSBEGIN 1
HIEBEGIN 1
NETPARAM 1

N 2 ATOE 1 (1882)
Msg Searching paths
N 3 SHP1C 2 [518,171] (10)
N 4 EXT 1 1  [1] 1 (10)
Msg Depth Partition
C 3 GENLAYER 4 (10)
P 1 MPER 2 (10)
Msg Reordering
N 5 REOR 4 1 (10)
Msg Strong Components
P 2 NUMB 5 [2,1] (10)
P 3 INVPERM 2 (10)
Msg Reordering
N 6 REOR 5 3 (10)
Msg Depth Partition
C 4 GENLAYER 6 (10)
E 6 LAYERSNY 4
E 6 DRAW 4 0 0
