# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face_ver.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(855, 428)
        self.btnOK = QtWidgets.QDialogButtonBox(Dialog)
        self.btnOK.setGeometry(QtCore.QRect(90, 370, 341, 32))
        self.btnOK.setOrientation(QtCore.Qt.Horizontal)
        self.btnOK.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnOK.setObjectName("btnOK")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(50, 70, 381, 261))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(70, 100, 131, 26))
        self.label.setObjectName("label")
        self.btnSelectModel = QtWidgets.QPushButton(self.groupBox)
        self.btnSelectModel.setGeometry(QtCore.QRect(210, 100, 101, 28))
        self.btnSelectModel.setObjectName("btnSelectModel")
        self.btnSelectPic1 = QtWidgets.QPushButton(self.groupBox)
        self.btnSelectPic1.setGeometry(QtCore.QRect(210, 140, 101, 28))
        self.btnSelectPic1.setObjectName("btnSelectPic1")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(90, 140, 96, 26))
        self.label_2.setObjectName("label_2")
        self.btnSelectPic2 = QtWidgets.QPushButton(self.groupBox)
        self.btnSelectPic2.setGeometry(QtCore.QRect(210, 180, 101, 28))
        self.btnSelectPic2.setObjectName("btnSelectPic2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(87, 180, 96, 26))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(70, 55, 121, 31))
        self.label_4.setObjectName("label_4")
        self.cmboxModelSel = QtWidgets.QComboBox(self.groupBox)
        self.cmboxModelSel.setGeometry(QtCore.QRect(210, 61, 101, 21))
        self.cmboxModelSel.setObjectName("cmboxModelSel")
        self.cmboxModelSel.addItem("")
        self.cmboxModelSel.addItem("")
        self.cmboxModelSel.addItem("")
        self.cmboxModelSel.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(450, 90, 181, 231))
        self.groupBox_2.setObjectName("groupBox_2")
        self.imageOne_label = QtWidgets.QLabel(self.groupBox_2)
        self.imageOne_label.setGeometry(QtCore.QRect(20, 60, 141, 151))
        self.imageOne_label.setObjectName("imageOne_label")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(650, 90, 181, 231))
        self.groupBox_3.setObjectName("groupBox_3")
        self.imageTwo_label = QtWidgets.QLabel(self.groupBox_3)
        self.imageTwo_label.setGeometry(QtCore.QRect(20, 60, 141, 151))
        self.imageTwo_label.setObjectName("imageTwo_label")

        self.retranslateUi(Dialog)
        self.btnOK.accepted.connect(Dialog.accept)
        self.btnOK.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Face Verify"))
        Dialog.setWindowIcon(QIcon('UI/icon/verify.png'))
        self.groupBox.setTitle(_translate("Dialog", "select your parameter"))
        self.label.setText(_translate("Dialog", "Model weights:"))
        self.btnSelectModel.setText(_translate("Dialog", "select..."))
        self.btnSelectPic1.setText(_translate("Dialog", "select..."))
        self.label_2.setText(_translate("Dialog", "Image One:"))
        self.btnSelectPic2.setText(_translate("Dialog", "select..."))
        self.label_3.setText(_translate("Dialog", "Image Two:"))
        self.label_4.setText(_translate("Dialog", "Model backbone:"))
        self.cmboxModelSel.setItemText(0, _translate("Dialog", "VGG"))
        self.cmboxModelSel.setItemText(1, _translate("Dialog", "Inception V2"))
        self.cmboxModelSel.setItemText(2, _translate("Dialog", "Resnet"))
        self.cmboxModelSel.setItemText(3, _translate("Dialog", "Mobilenet"))
        self.groupBox_2.setTitle(_translate("Dialog", "selected image one"))
        self.imageOne_label.setText(_translate("Dialog", "select image one"))
        self.groupBox_3.setTitle(_translate("Dialog", "selected image two"))
        self.imageTwo_label.setText(_translate("Dialog", "select image one"))
