# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gen_database.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(572, 399)
        self.btnOK = QtWidgets.QDialogButtonBox(Dialog)
        self.btnOK.setGeometry(QtCore.QRect(30, 340, 341, 32))
        self.btnOK.setOrientation(QtCore.Qt.Horizontal)
        self.btnOK.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnOK.setObjectName("btnOK")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(50, 50, 461, 281))
        self.groupBox.setObjectName("groupBox")
        self.btn_generateDb = QtWidgets.QPushButton(self.groupBox)
        self.btn_generateDb.setGeometry(QtCore.QRect(200, 210, 121, 28))
        self.btn_generateDb.setObjectName("btn_generateDb")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(50, 160, 101, 26))
        self.label_3.setObjectName("label_3")
        self.btn_sourceParh = QtWidgets.QPushButton(self.groupBox)
        self.btn_sourceParh.setGeometry(QtCore.QRect(200, 160, 121, 28))
        self.btn_sourceParh.setObjectName("btn_sourceParh")
        self.btn_selectMolW = QtWidgets.QPushButton(self.groupBox)
        self.btn_selectMolW.setGeometry(QtCore.QRect(200, 110, 121, 28))
        self.btn_selectMolW.setObjectName("btn_selectMolW")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 210, 141, 26))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 110, 151, 26))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(40, 60, 121, 26))
        self.label_4.setObjectName("label_4")
        self.cmbox_selMol = QtWidgets.QComboBox(self.groupBox)
        self.cmbox_selMol.setGeometry(QtCore.QRect(200, 60, 121, 22))
        self.cmbox_selMol.setObjectName("cmbox_selMol")
        self.cmbox_selMol.addItem("")
        self.cmbox_selMol.addItem("")
        self.cmbox_selMol.addItem("")
        self.cmbox_selMol.addItem("")

        self.retranslateUi(Dialog)
        self.btnOK.accepted.connect(Dialog.accept)
        self.btnOK.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Generate Database"))
        Dialog.setWindowIcon(QIcon('UI/icon/database.png'))
        self.groupBox.setTitle(_translate("Dialog", "select your parameter"))
        self.btn_generateDb.setText(_translate("Dialog", "select..."))
        self.label_3.setText(_translate("Dialog", "Raw Data:"))
        self.btn_sourceParh.setText(_translate("Dialog", "select..."))
        self.btn_selectMolW.setText(_translate("Dialog", "select..."))
        self.label_2.setText(_translate("Dialog", "Database path:"))
        self.label.setText(_translate("Dialog", "Model weight path:"))
        self.label_4.setText(_translate("Dialog", "Model backbone:"))
        self.cmbox_selMol.setItemText(0, _translate("Dialog", "VGG"))
        self.cmbox_selMol.setItemText(1, _translate("Dialog", "Inception V2"))
        self.cmbox_selMol.setItemText(2, _translate("Dialog", "Resnet"))
        self.cmbox_selMol.setItemText(3, _translate("Dialog", "Mobilenet"))
