# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimediaWidgets import QVideoWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1070, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupbox_workStation = QtWidgets.QGroupBox(self.centralwidget)
        self.groupbox_workStation.setGeometry(QtCore.QRect(40, 180, 361, 101))
        self.groupbox_workStation.setObjectName("groupbox_workStation")
        self.btn_Run = QtWidgets.QPushButton(self.groupbox_workStation)
        self.btn_Run.setGeometry(QtCore.QRect(20, 50, 93, 28))
        self.btn_Run.setObjectName("btn_Run")
        self.btn_Stop = QtWidgets.QPushButton(self.groupbox_workStation)
        self.btn_Stop.setGeometry(QtCore.QRect(130, 50, 93, 28))
        self.btn_Stop.setObjectName("btn_Stop")
        self.btn_Reset = QtWidgets.QPushButton(self.groupbox_workStation)
        self.btn_Reset.setGeometry(QtCore.QRect(240, 50, 93, 28))
        self.btn_Reset.setObjectName("btn_Reset")
        self.frame_outputInfo = QtWidgets.QFrame(self.centralwidget)
        self.frame_outputInfo.setGeometry(QtCore.QRect(40, 340, 361, 161))
        self.frame_outputInfo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_outputInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_outputInfo.setObjectName("frame_outputInfo")
        self.textBro_outputInfo = QtWidgets.QTextBrowser(self.frame_outputInfo)
        self.textBro_outputInfo.setGeometry(QtCore.QRect(0, 0, 361, 161))
        self.textBro_outputInfo.setObjectName("textBro_outputInfo")
        self.label_outputInfo = QtWidgets.QLabel(self.centralwidget)
        self.label_outputInfo.setGeometry(QtCore.QRect(40, 300, 161, 31))
        self.label_outputInfo.setObjectName("label_outputInfo")
        self.label_statusInfo = QtWidgets.QLabel(self.centralwidget)
        self.label_statusInfo.setGeometry(QtCore.QRect(40, 40, 151, 21))
        self.label_statusInfo.setObjectName("label_statusInfo")
        self.textBro_statusInfo = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBro_statusInfo.setGeometry(QtCore.QRect(40, 70, 361, 81))
        self.textBro_statusInfo.setObjectName("textBro_statusInfo")
        self.widget_player = QVideoWidget(self.centralwidget)
        self.widget_player.setGeometry(QtCore.QRect(490, 110, 451, 351))
        self.widget_player.setObjectName("widget_player")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 26))
        self.menubar.setObjectName("menubar")
        self.menuFunction = QtWidgets.QMenu(self.menubar)
        self.menuFunction.setObjectName("menuFunction")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFace_Recognition = QtWidgets.QAction(MainWindow)
        self.actionFace_Recognition.setObjectName("actionFace_Recognition")
        self.actionFace_Verify = QtWidgets.QAction(MainWindow)
        self.actionFace_Verify.setObjectName("actionFace_Verify")
        self.actionTrain_Model = QtWidgets.QAction(MainWindow)
        self.actionTrain_Model.setObjectName("actionTrain_Model")
        self.actionGenerate_db = QtWidgets.QAction(MainWindow)
        self.actionGenerate_db.setObjectName("actionGenerate_db")
        self.menuFunction.addAction(self.actionFace_Recognition)
        self.menuFunction.addAction(self.actionFace_Verify)
        self.menuFunction.addAction(self.actionTrain_Model)
        self.menuFunction.addSeparator()
        self.menuFunction.addAction(self.actionGenerate_db)
        self.menubar.addAction(self.menuFunction.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupbox_workStation.setTitle(_translate("MainWindow", "Work Station"))
        self.btn_Run.setText(_translate("MainWindow", "Run"))
        self.btn_Stop.setText(_translate("MainWindow", "Stop"))
        self.btn_Reset.setText(_translate("MainWindow", "Reset"))
        self.label_outputInfo.setText(_translate("MainWindow", "Output Information"))
        self.label_statusInfo.setText(_translate("MainWindow", "Status Information"))
        self.menuFunction.setTitle(_translate("MainWindow", "Function"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionFace_Recognition.setText(_translate("MainWindow", "Face Recognition"))
        self.actionFace_Verify.setText(_translate("MainWindow", "Face Verify"))
        self.actionTrain_Model.setText(_translate("MainWindow", "Train Model"))
        self.actionGenerate_db.setText(_translate("MainWindow", "Generate Database"))
